server:
  port: 8088
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/score
      username: root
      password: tyy521516
  #Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  #邮箱验证码
  mail:
    #平台地址，这里用的是qq邮箱，使用其他邮箱请更换
    host: smtp.qq.com
    #改成自己的邮箱
    username : 3486233421@qq.com
    #发送短信后它给你的授权码 填写到这里
    password: ujbazfomhjhmcjda
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    ##编码格式
    default-encoding: utf-8
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    cache:
      redis:
        time-to-live: 1800000
  #文件上传和下载
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
#文件上传的位置
file:
  ###静态资源对外暴露的访问路径
  staticAccessPath: /api/file/**
  ###静态资源实际存储路径
  uploadFolder: E:/项目/score/doc/